<a href="https://colab.research.google.com/github/Mounikamuniganti/DAV_Fundamentals/blob/main/Feature_Engineering_Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basic EDA**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind, chisquare, chi2_contingency

In [2]:
data=pd.read_csv("https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/018/746/original/loan.csv?1666170299")

In [3]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [5]:
data.shape

(614, 13)

In [6]:
data.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [7]:
data.describe(include='object')

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
count,614,601,611,599,614,582,614,614
unique,614,2,2,4,2,2,3,2
top,LP001002,Male,Yes,0,Graduate,No,Semiurban,Y
freq,1,489,398,345,480,500,233,422

In [8]:
data["Gender"].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

# **`Feature Engineering_1_Assignment`**

# **Q1. Difference in income groups**

We believe that the loan.csv data shows that unmarried men are in a different income group than both married and unmarried women.

To prove this, would a t-test be more appropriate or a chi-square test?

Carry out the test on the 'ApplicantIncome' column for the two groups and report the p-value. Also, report your interpretation.

Note: Assume a confidence level of 95% and round off the p-value to 2 decimal places.

In [21]:
data['Married'].value_counts()

Married
Yes    398
No     213
Name: count, dtype: int64

In [12]:
pd.crosstab(index=data['Gender'],columns=data['Loan_Status'])

Loan_Status    N    Y
Gender
Female        37   75
Male         150  339

In [13]:
pd.crosstab(index=data['Married'],columns=data['Loan_Status'])

Loan_Status    N    Y
Married
No            79  134
Yes          113  285

In [23]:
# Load the Income data for unmarried men
unmarried_men = data[(data["Gender"] == "Male") & (data["Married"] == "No")]["ApplicantIncome"]
unmarried_men.dropna(inplace=True)
print("Number of unmarried men datapoints: ", len(unmarried_men))

# Load the data for both married and unmarried women
women = data[(data["Gender"] == "Female")]["ApplicantIncome"]
women.dropna(inplace=True)
print("Number of women datapoints: ", len(women))

# Perform a t-test since the incomes are a continuous variable.
p_value = ttest_ind(unmarried_men, women)[1]
print("p_value :" ,round(p_value,2))

if p_value > 0.05:
 print('Since p_value > 0.05 we fail to reject the null hypothesis.')

else:
 print('Since p_value < 0.05 we reject the null hypothesis.')

Number of unmarried men datapoints:  130
Number of women datapoints:  112
p_value : 0.26
Since p_value > 0.05 we fail to reject the null hypothesis.

<ipython-input-23-7ca39f50fed8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unmarried_men.dropna(inplace=True)
<ipython-input-23-7ca39f50fed8>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  women.dropna(inplace=True)

# **Q2. Graduate unmarried men**

We believe that the loan.csv data shows that graduate unmarried men are in a different income group than both married and unmarried graduate women.

To prove this, would a t-test be more appropriate or a chi-square test?

Carry out the test on the 'ApplicantIncome' column for the two groups and report the p-value. Also report your interpretation.

Note: Assume a confidence level of 95% and round off the p-value to 2 decimal places.

In [24]:

# Load the Income data for graduate unmarried men
unmarried_grad_men = data[(data["Gender"] == "Male") & (data["Married"] == "No") & (data["Education"] == "Graduate")]["ApplicantIncome"]
unmarried_grad_men.dropna(inplace=True)
print("Number of unmarried men datapoints: ", len(unmarried_grad_men))

# Load the data for both married and unmarried graduate women
women_grad = data[(data["Gender"] == "Female") & (data["Education"] == "Graduate")]["ApplicantIncome"]
women_grad.dropna(inplace=True)
print("Number of women datapoints: ", len(women_grad))

# Perform a t-test since the incomes are a continuous variable.
p_value = ttest_ind(unmarried_grad_men, women_grad)[1]
print("p_value :" ,round(p_value,2))

if p_value > 0.05:
 print('Since p_value > 0.05 we fail to reject the null hypothesis.')

else:
 print('Since p_value < 0.05 we reject the null hypothesis.')

Number of unmarried men datapoints:  99
Number of women datapoints:  92
p_value : 0.08
Since p_value > 0.05 we fail to reject the null hypothesis.

<ipython-input-24-cc5850f6f458>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unmarried_grad_men.dropna(inplace=True)
<ipython-input-24-cc5850f6f458>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  women_grad.dropna(inplace=True)

# **Q3. Get a loan**

We believe that the loan.csv data shows that graduate unmarried men are more likely to get a loan than graduate women.

To prove this, would a t-test be more appropriate or a chi-square test?

Perform the appropriate statistical test on the 'Loan_Status' column for the two groups, report the p-value, and provide an interpretation of the results, considering a confidence level of 95%.

Note: Round the p-value to two decimal places.

In [26]:
#Null hypothesis (H0) : The likelihood of getting a loan is equal for both groups.
#Alternate hypothesis (Ha) : The likelihood of getting a loan is not equal for both groups.

# Add a column indicating that the entry contains graduate and unmarried men
data['GraduateUnmarriedMen'] = (data["Gender"] == "Male") & (data["Married"] == "No") & (data["Education"] == "Graduate")
graduate_unmarried_men = data[(data['GraduateUnmarriedMen'] == True)]
print('Number of graduate married men datapoints:',len(graduate_unmarried_men))

# Load the data for graduate women
data['GraduateWomen'] = (data["Gender"] == "Female") & (data["Education"] == "Graduate")
graduate_women = data[(data["GraduateWomen"] == True)]
print('Number of graduate women datapoints:',len(graduate_women))

data = data[(data['GraduateUnmarriedMen'] == True) | (data['GraduateWomen'] == True)]

print(data)

# Perform a chi-square test since the loan_Status is a categorical variable.
contingency = pd.crosstab(data['GraduateUnmarriedMen'], data['Loan_Status'])
print('\n',contingency,'\n')
p_value = chi2_contingency(contingency)[1]
print('p-value:',round(p_value,2))

if p_value > 0.05:
 print('Since p_value > 0.05 we fail to reject the null hypothesis.')

else:
 print('Since p_value < 0.05 we reject the null hypothesis.')

Number of graduate married men datapoints: 99
Number of graduate women datapoints: 92
      Loan_ID  Gender Married Dependents Education Self_Employed  \
0    LP001002    Male      No          0  Graduate            No
4    LP001008    Male      No          0  Graduate            No
13   LP001029    Male      No          0  Graduate            No
15   LP001032    Male      No          0  Graduate            No
17   LP001036  Female      No          0  Graduate            No
..        ...     ...     ...        ...       ...           ...
600  LP002949  Female      No         3+  Graduate           NaN
603  LP002958    Male      No          0  Graduate            No
604  LP002959  Female     Yes          1  Graduate            No
609  LP002978  Female      No          0  Graduate            No
613  LP002990  Female      No          0  Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
4               6000                0.0       141.0             360.0
13              1853             2840.0       114.0             360.0
15              4950                0.0       125.0             360.0
17              3510                0.0        76.0             360.0
..               ...                ...         ...               ...
600              416            41667.0       350.0             180.0
603             3676             4301.0       172.0             360.0
604            12000                0.0       496.0             360.0
609             2900                0.0        71.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status  GraduateUnmarriedMen  \
0               1.0         Urban           Y                  True
4               1.0         Urban           Y                  True
13              1.0         Rural           N                  True
15              1.0         Urban           Y                  True
17              0.0         Urban           N                 False
..              ...           ...         ...                   ...
600             NaN         Urban           N                 False
603             1.0         Rural           Y                  True
604             1.0     Semiurban           Y                 False
609             1.0         Rural           Y                 False
613             0.0     Semiurban           N                 False

     GraduateWomen
0            False
4            False
13           False
15           False
17            True
..             ...
600           True
603          False
604           True
609           True
613           True

[191 rows x 15 columns]

 Loan_Status            N   Y
GraduateUnmarriedMen
False                 31  61
True                  37  62

p-value: 0.7
Since p_value > 0.05 we fail to reject the null hypothesis.

# **Q4. Create new feature**

We have been given a dataset containing the details of the people applied for loan.

dataset: loan.csv

We wish to create a new feature called 'NewFeature' using a linear combination of the features ApplicantIncome, LoanAmount and Credit_History, with weights 1, 3 and 7000,

i.e., data['NewFeature'] = (data["ApplicantIncome"]) + (3 * data["LoanAmount"]) + (7000 * data["Credit_History"]).

Since 'NewFeature' is a numerical feature, convert it to a categorical feature by checking whether 'NewFeature' is greater than 0.25 times the mean of 'NewFeature'. Call this feature 'Separator'.

Perform a chi-square test on the contingency table formed by the features 'Loan_Status' and 'Separator' and report the p-value. Also report your interpretation.

Note: Drop all the rows having 'na' values before performing any operation on the data and assume the significance level to be 5%. Also, round off the p-value to four decimal places.

In [15]:
'''Based on the given question, we define our hypothesis as:

H0: The features Separator and Loan_Status are independent.
Ha: The features Separator and Loan_Status are dependent on each other.
We can perform Chi squared test on this data using the following code:
'''

# Add a column indicating that the entry contains graduate and married men
data.dropna(inplace=True)
data['NewFeature'] = (data["ApplicantIncome"]) + (3 * data["LoanAmount"]) + (7000 * data["Credit_History"])
data['Separator'] = data['NewFeature'] > (data['NewFeature'].mean()*0.25)

# Perform a chi-square test since the incomes are a continuous variable.
contingency = pd.crosstab(data['Separator'], data['Loan_Status'])
print(contingency)

# p-value calculation
p_value = chi2_contingency(contingency)[1]

print(p_value)
if(p_value < 0.05):
  print("Since p-value < 0.05, the two features 'Separator' and 'Loan_Status' are dependent.")
else:
  print("Since p-value > 0.05, the two features 'Separator' and 'Loan_Status' are independent.")

Loan_Status    N    Y
Separator
False         11    2
True         137  330
7.72913548149729e-05
Since p-value < 0.05, the two features 'Separator' and 'Loan_Status' are dependent.

# **Q5. Numerical to categorical**

We have been given a dataset containing the details of the people applied for loan.

dataset: loan.csv

Which of the following features can be converted from a numerical feature to a categorical feature simply by renaming the values?

In [ ]:
Credit_History - Since the Credit_History contains the values that are either 0.0 or 1.0, which can be relabeled as False and True, respectively.
Therefore,it can be converted from a numerical feature to a categorical feature simply by renaming the values.

# **`Feature Engineering_2_Assignment`**

# **Q1. Female applicant**

In the loan.csv dataset, we wish to test the hypothesis that among all loan applicants who were rejected for a loan, applicants with a credit history of 1 are more likely to be female.

Use a chi-square test to verify this claim (Ensure that you drop all nan rows), and report your interpretation.

Note: Use a significance level of 5%.

In [20]:
#Ho: 'Credit_History' and 'Gender' are independent.
#HA: 'Credit_History' and 'Gender' are dependent.

# data of all the rejected applicants
chn = data[(data["Loan_Status"] == "N")]

#dropping na values
chn = chn.dropna()

#contingency table
contingency = pd.crosstab(chn['Gender'], chn['Credit_History'])
print(contingency)

#p-value
print('p-value:', round(chi2_contingency(contingency)[1],3))

#p_value----is high, so fail o reject the null hypothesis

Credit_History  0.0  1.0
Gender
Female           13   19
Male             50   66
p-value: 0.961
we reject the null hypothesis.

In [21]:
0.961>0.05

True

# **Q2. Univariate Analysis**

Which type of graphical techniques can be applied to analyze Continuous and Categorical features?

1.Box plot for continuous variable

2.Pie chart for continuous variable

3.Bar plot for categorical variable

4.Histogram for continuous variable

5.Q-Q plot specifically for outliers in Continuous variable.

In [ ]:
Box plot for continuous variable

Bar plot for categorical variable

Histogram for continuous variable

Q-Q plot specifically for outliers in Continuous variable.

# **Q3. Co2 Emissions**

The below data represents the carbon dioxide emission from vehicles in grams/per km. There are a few missing values present in the data.

What will be the imputing strategy that we can use?

data=[50,196,221,136,255,NaN,230,252,267,212,NaN,359,328,200,500,624,NaN,236,289,300,366]

import numpy as np

from sklearn.impute import SimpleImputer

data=np.array(data)

imputer = SimpleImputer(strategy = “________”)

data1= imputer.fit_transform(data.reshape(-1,1))

In [ ]:
median

# **Q4. Missing_values**

You are cleaning up a DataFrame that has almost 5000 observations and you notice that one of the categorical columns contains 1512 missing values.

What strategy should you apply to deal with these missing values?

In [ ]:
Impute the missing values with the most_frequent value.

# **Q5. Imputer Works**

What does the following code snippet do?

from sklearn.impute

import SimpleImputer

imp_mean = SimpleImputer( strategy='mean')

imp_mean.fit(data)

imputed_train_df = imp_mean.transform(data)

In [ ]:
Calculates the mean of the non-missing values in a column and then replacing the missing values within each column separately